from stereolabs/zed:3.4-runtime-cuda11.0-ubuntu18.04

RUN apt install python3 python3-pip

RUN apt-get python3-opencv python3-numpy

RUN pip3 install awsiotsdk boto3

COPY ./video_processing_test/image_test.py /image_test.py

CMD ["/image_test.py"]