FROM nvidia/cuda:10.2-base

CMD nvidia-smi

RUN apt-get update && apt-get install --no-install-recommends --no-install-suggests -y curl

RUN curl -O https://cvsg-artifacts.s3-ap-southeast-2.amazonaws.com/ZED_SDK_Tegra_JP45_v3.5.0.run

RUN chmod +x ZED_SDK_Tegra_JP45_v3.5.0.run

RUN ./ZED_SDK_Tegra_JP45_v3.5.0.run

RUN apt install python3 python3-pip && pip3 install opencv-python awsiotsdk boto3 numpy

COPY ./video_processing_test/image_test.py /image_test.py

CMD ["/image_test.py"]